name: Playwright Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Install dependencies for API
        run: dotnet restore
        working-directory: ./API/Contacts

      - name: Install dependencies for UI
        run: npm install
        working-directory: ./UI/Contacts/

      - name: Install dependencies for Tests
        run: npm install
        working-directory: ./Tests

      - name: Start API
        run: |
          nohup dotnet watch run --project ./API/Contacts > api.log 2>&1 &
        working-directory: ./API/Contacts

      - name: Start UI
        run: |
          nohup ng serve > ui.log 2>&1 &
        working-directory: ./UI/Contacts

      - name: Wait for API and UI to be ready
        run: |
          echo "Waiting for API to be ready..."
          while ! curl -s http://localhost:5070 > /dev/null; do sleep 1; done
          echo "Waiting for UI to be ready..."
          while ! curl -s http://localhost:4200 > /dev/null; do sleep 1; done

      - name: Install Playwright browsers
        run: npx playwright install
        working-directory: ./Tests

      - name: Run Playwright tests
        run: npm run regression
        working-directory: ./Tests/
